title: VirtualLeverless Receiver
description: A collection of patch notes and releases for VirtualLeverless Receiver.
theme: minima
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-fontawesome